### ISSUE TITLE
suggestions for SnackVar optimization

### ISSUE THREAD

**Issue by raphaelleman** [Young-gonKim/SnackVar#4]
Hi,
We use SnackVar v2.3.1 since three mounths and we have analyzed about 100 patients with this tool. After this feedback from experience, our technicians have some suggestions to improve the use of SnackVar:
- Display on the main window of SnackVar the values of setting paramaters in particular the cutoff for double peak detection.
- Sometimes SnackVar trims the sequences at delins level, and during the import of sequence the manually trimmed sequences are not saved, so we have to trimed twice, but maybe you manage it in the version 2.4.0. 
- Do you think possible that SnackVar can deal with pseudo-genes sequences, for example make the difference between the _PMS2_ gene sequence and its peudo-gene _PMS2CL_ 
- The last, in French we use comma instead of dot for decimal separator, thus our machines try automatically to convert the value of cutoff for double peak detection in French format which induces a bug when we confirm SnackVar settings. So it would be possible to define this value as a string and not as a float, but it's probably a too specific "French" problem.

**Comment by Young-gonKim** [comment]
Thank you for your valuable feedbacks. 
For the suggestions 1, 4 I guess I could reflect those in the next version. I will try to find time for those soon. 
To reflect the suggestion 2, the trimming locations should be saved in separate data structure since they cannot be saved at the trace files(.ab1 files). So additional functions such as save/load project deems to be required. I will rethink about this option. 
For the suggestion 3, pseudogenes are always tricky to handle. I think we could choose the original gene and its pseudogene alternatively as the reference sequence and compare the result, using existing functions of SnackVar. However, in many situations, I guess we will need other tools such as genome browsers adjunctively to SnackVar to analyze sequences that have pseudogene counterparts.

**Comment by raphaelleman** [comment]
Hi, 
Thank you for your assistance,
One of our technicians is asking to have two different values of the cutoff for double peak detection, for the forward and reverse sequences

**Comment by raphaelleman** [comment]
Hi
Hope you're fine,
It is possible to display the gene name plus the transcript ID on the reports generated by SnackVar.

**Comment by Young-gonKim** [comment]
I've uploaded 2.4.1 version and the changes can be found at bottom of the Readme page. 
Specifically, I've reflected all of the suggestions above except for the pseudogene issue and saving trimmed trace files. 
These two things would require major change of the program and please understand me that  I couldn't find time for them after moving my workplace.
I believe that SnackVar became much better because of your suggestions. Thank you!

**Comment by raphaelleman** [comment]
Hi,
A great thank you for this new version.
